project:
  type: website
  output-dir: docs

website:
  title: "String Theory and Quantum Gravity"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

render:
  latex:
    engine: pdflatex
    options: [--shell-escape]

